### ISSUE TITLE
Some visual issues on the bluetooth settings page

### ISSUE THREAD

**Issue by Fatih20** [elementary/switchboard-plug-bluetooth#87]
![Screenshot from 2019-09-13 19 16 01](https://user-images.githubusercontent.com/51940383/64861826-328d4d80-d65b-11e9-9290-f61fd3522afd.png)
I don't think the gray rectangle around the 3 dots that is used to configure the device is supposed to exist.

**Comment by danrabbit** [comment]
This is a keyboard focus indicator. It is intentional

**Comment by Fatih20** [comment]
I think this could be made to look better. The edge of the rectangle is too close to the dots make it doesn't look aesthetically pleasing and makes it look like an unintentional mistake.

**Comment by 4jNsY6fCVqZv** [comment]
I also have the feeling that the visual solution is not as appealing and self-explanatory for me so far.

My scenario:
I have exactly one device that is connected via Bluetooth. In addition, I never use the keyboard for navigation. Nevertheless, I see the grey bar and the grey dots as default. However, when I use the keyboard to navigate, the bars and dots turn blue. I understand the latter because it indicates that the keyboard is in play. What the grey bar and the grey dots want to tell me is unfortunately not clear to me, especially because there are no different elements to choose from.

Could you please explain the concept behind it?

Maybe there is also a visual solution that is more appealing and has the same functionality? For example, if the dots wouldn't stand out like that or the square box around them disappears, things look different.
